name: flutter_chat_app
description: Chat application with Flutter and Firebase.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  dartz: ^0.10.1
  get_it: ^7.7.0
  go_router: ^13.2.4
  flutter_riverpod: ^2.5.1
  firebase_auth: ^4.19.2
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.0.1
  firebase_messaging: ^14.8.2
  cloud_firestore: ^4.17.0
  http: ^1.2.1
  fluttertoast: ^8.2.5
  image_picker: ^1.1.0
  shared_preferences: ^2.2.3
  firebase_storage: ^11.7.2
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - images/
