// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDodxupFfVuRfF3lkI2Jl9XVXqUiAt6K3g',
    appId: '1:815480470620:android:6aa0c4180f27bb48447a99',
    messagingSenderId: '815480470620',
    projectId: 'flutter-chat-app-e5f6b',
    storageBucket: 'flutter-chat-app-e5f6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSLfLn3Ch1hPfDyvBA5n99RODLAyljTNs',
    appId: '1:815480470620:ios:193bab68f1f53305447a99',
    messagingSenderId: '815480470620',
    projectId: 'flutter-chat-app-e5f6b',
    storageBucket: 'flutter-chat-app-e5f6b.appspot.com',
    androidClientId: '815480470620-9ujbjj7jf6oa22c3fpijd8c5jkp28bdb.apps.googleusercontent.com',
    iosClientId: '815480470620-be94afqmp5levo2ht321dt87qlqgvbqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

}